### ISSUE TITLE
Success of gnatsd tests depends on go-nats version

### ISSUE THREAD

**Issue by h4xnoodle** [nats-io/nats-server#866]
- [X] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `gnatsd -DV` output
 - [X] Included a [Minimal, Complete, and Verifiable example] (http://stackoverflow.com/help/mcve)
 
#### Versions of `gnatsd` and affected client libraries used:
gnatsd 1.3.0, latest master go-nats as recommended in readme

#### OS/Container environment:
Mac OS X 10.13.6

#### Steps or code to reproduce the issue:
1. Checkout tag v1.3.0 `git checkout v1.3.0`
2. Follow readme and `go get github.com/nats-io/go-nats` or `go get -t ./...` to obtain latest go-nats
3. Run tests

#### Expected result:
Tests pass. `go-nats` is locked/go dep/modules used such that the tests for 1.3.0 can still pass.
 
#### Actual result:
Symptom that suggests the fixture certificates had expired. After checking them all, that was not the case.

```shell
go test ./...
?   	github.com/nats-io/gnatsd	[no test files]
ok  	github.com/nats-io/gnatsd/conf	0.011s
ok  	github.com/nats-io/gnatsd/logger	0.630s
--- FAIL: TestConfigReloadRotateTLS (0.06s)
    reload_test.go:329: Error creating client: x509: certificate signed by unknown authority
--- FAIL: TestConfigReloadEnableTLS (0.06s)
    reload_test.go:396: Error creating client: x509: certificate signed by unknown authority
--- FAIL: TestConfigReloadDisableTLS (0.05s)
    reload_test.go:421: Error creating client: x509: certificate signed by unknown authority
--- FAIL: TestConfigReloadChangePermissions (0.03s)
    reload_test.go:1010: Expected permissions violation error, got nats: Permissions Violation for Subscription to "_INBOX.>" (sid 1)
FAIL
FAIL	github.com/nats-io/gnatsd/server	28.583s
ok  	github.com/nats-io/gnatsd/server/pse	(cached)
--- FAIL: TestTLSBadAuthError (0.09s)
    tls_test.go:286: Excpected and auth violation, got nats: Authorization Violation
FAIL
FAIL	github.com/nats-io/gnatsd/test	34.073s
?   	github.com/nats-io/gnatsd/util	[no test files]
```

Workaround:
The last commit of go-nat that works with 1.3.0 seems to be https://github.com/nats-io/go-nats/commit/21aecb5f7f78c45d4aed681a53d45fe9681ad537. We check that out to run tests.

**Comment by kozlovic** [comment]
We made a change to go-nats that causes to not skip server certificate (unless explicitly configured to do so): https://github.com/nats-io/go-nats/pull/420

Server tests were updated to reflect this change: https://github.com/nats-io/gnatsd/pull/863

**Comment by h4xnoodle** [comment]
@kozlovic yes, this makes sense. However, if one wishes to use 1.3.0, the most recent release, and we ask them to obtain `go-nats` latest, the tests cannot pass. The user of 1.3.0 must then find and checkout a SHA for go-nats which works. I would recommend we use go dep or modules to help here, for the tests.

**Comment by derekcollison** [comment]
I am closing this for now, we have begun the switch over to go modules starting with v2.0.0 release.
